### ISSUE TITLE
Update Js-sdsl to 4.1.3

### ISSUE THREAD

**Issue by ZLY201** [redboltz/number-allocator#29]
Hey！I'm the developer of Js-sdsl. 

Now, we published the version 4.1.3. 

This version not only supports bidirectional iterators, but also doubles the performance compared to the 2.x version.

I think update it to 4.1.3 is a good choice to improve your package.

Office website: https://js-sdsl.github.io/

**Comment by redboltz** [comment]
Thank you @ZLY201 ! It is a great improvement.

I tried it and got error. See #30.

https://github.com/redboltz/number-allocator/blob/9bcfebf68cc9e15b58627faac1081f4bc111286a/lib/number-allocator.js#L99-L103

This is the first trial to use iterator.
I compared the return value of lowerBound() to `this.ss.end()`

Then got the following error:

https://github.com/redboltz/number-allocator/runs/8057549850?check_suite_focus=true#step:5:19

```
/home/runner/work/number-allocator/number-allocator/node_modules/js-sdsl/dist/cjs/container/TreeContainer/Base/TreeIterator.js:42
            throw new TypeError(`Obj's constructor is not ${this.constructor.name}!`);
            ^

TypeError: Obj's constructor is not OrderedSetIterator!
    at OrderedSetIterator.equals (/home/runner/work/number-allocator/number-allocator/node_modules/js-sdsl/dist/cjs/container/TreeContainer/Base/TreeIterator.js:42:[19](https://github.com/redboltz/number-allocator/runs/8057549850?check_suite_focus=true#step:5:20))
    at NumberAllocator.use (/home/runner/work/number-allocator/number-allocator/lib/number-allocator.js:103:12)
    at Object.<anonymous> (/home/runner/work/number-allocator/number-allocator/test/typescript/test.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:[28](https://github.com/redboltz/number-allocator/runs/8057549850?check_suite_focus=true#step:5:29)3:19)
```

It seems that the error means iterators type mismatch.
I added debug print to the following line (actually transpiled JS code)
https://github.com/js-sdsl/js-sdsl/blob/v4.1.3/src/container/TreeContainer/Base/TreeIterator.ts#L44-L46

```
    equals(obj) {
        if (obj.constructor.name !== this.constructor.name) {
            console.log(obj.constructor.name);
            console.log(this.constructor.name);
            throw new TypeError(`Obj's constructor is not ${this.constructor.name}!`);
        }
```

The result is as follows:

`obj.constructor.name` is `Interval`
`this.constructor.name` is `OrderedSetIterator`

I guess that I misuse `end()` function. Could you help me?

**Comment by ZLY201** [comment]
Please see https://js-sdsl.github.io/#/start/iterator?id=bidirectional-iterator first.

Because js does not provide overloading of `==` operator, we use equals function to instead it.

Iterator.equals must have a param with the same iterator type.

For example:

```javascript
const key = new Interval(num, num);
const it = this.ss.lowerBound(key);
const end = this.ss.end();
if (it.equals(end) === false && it.pointer.equals(key) === true) {
    this.ss.eraseElementByIterator(it);  // faster than eraseElementByValue
    return true;
}
```

Hope this will help you!

**Comment by redboltz** [comment]
Thank you! I will fix the PR based on your information.

**Comment by ZLY201** [comment]
I forgot to tell you `eraseElementByIterator` will change the iterator to the next.

For example:

I have a container like [1, 2, 3].

I erase a iterator (named **It**) pointer to 2. Then container becomes [1, 3].

And **It** will pointer to 3.

Design ideas come from C++.

**Comment by redboltz** [comment]
Ok. thanks.

I have one more question.
Is there any recommended way to (deep) copy iterator ?

```js
let prev = it;
prev.pre();
```

When I do that, not only `prev` but also `it` is updated.
It is JS object copy behavior, but I want to deep copy.

Should I use deep copy package such as https://www.npmjs.com/package/rfdc

**Comment by ZLY201** [comment]
This design is in order to prevent iterator invalidation.

In your case, I think you can just save the value of `low` and `high` of pre iterator.

And when you erase an iterator, it will move to next, it's pre will not be invalid.

```javascript
mp = [0, 2, 3];
const it = mp.lowerBound(2);
mp.eraseElementBy(it);
// it pointer to 3.
// it.pre pointer to 0.
```

If you want to add 1 to mp, you can just use `setElement`.

Anyway, we don't suggest change the iterator.pointer directly.

**Comment by redboltz** [comment]
Finally, I updated my code and works fine. Thansk you for your support !



Stored only required high and low values.
https://github.com/redboltz/number-allocator/blob/542a6a5adfd853d310962a6d748f0db38cb9b382/lib/number-allocator.js#L195-L197

And move back to the next iterator as follows:
https://github.com/redboltz/number-allocator/blob/542a6a5adfd853d310962a6d748f0db38cb9b382/lib/number-allocator.js#L217

In this case, I need to update the low value of the next element without erase current element.

> If you want to add 1 to mp, you can just use setElement.
> Anyway, we don't suggest change the iterator.pointer directly.

IIUC, setElement is only for OrderedMap.
https://github.com/js-sdsl/js-sdsl/blob/main/src/container/TreeContainer/OrderedMap.ts#L129

OrderedSet doesn't have it.

I think that if I want to update (e.g. increment) the element of OrderedSet, I should do as follows:

1. Get the target element iterator
2. Get the value of the pointed element
3. Create the new value of the pointed element + 1
4. Erase the iterator
5. Insert the new value element

Pros:
If the new value should be inserted different position from the erased element, it works fine.
Cons:
Step 5 requires O(logN)

My approach is 

1. Get the target element iterator
2. Increment the pointed element via it.pointer

Pros:
Efficient. No extra O(logN) required.
Cons:
If the new value should be inserted different position from the erased element, the container would be invalid state (UB)

I use this approach only when the element position never change by value updating.

**Comment by ZLY201** [comment]
That's unsafe to `Increment the pointed element via it.pointer`, if you really want do that maybe you can use Iterator.node (that's a private member) and change `node.key`.

It may cause error in IDE, use `@ts-ignore` to ignore it.

However, we do not provide any guarantees for this behavior.

**Comment by redboltz** [comment]
Oh, really. 
Ok I removed all unsafe accesses.

https://github.com/redboltz/number-allocator/pull/30/commits/b15e038565a31d9e3823008b3217292cadbbccea
